name: Main workflow

on:
  pull_request:
  push:

jobs:
  plugin_test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: dprint --version
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: Test plugin
        run: |
          asdf plugin-add dprint $GITHUB_WORKSPACE
          make test

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: Run ShellCheck
        run: make lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: Run shfmt
        run: make fmt-check
